### ISSUE TITLE
UTM Doesn't Strip

### ISSUE THREAD

**Issue by cherylfahling** [newhouse/url-tracking-stripper#10]
UTM on this site isn't stripped:

http://www.foodandcraftoffers.com/offers.php?utm_source=&utm_campaign=&utm_medium=&utm_term=&r=131458383

**Comment by newhouse** [comment]
OMG, so sorry I didn't see this! Not sure why I wasn't receiving notifications...

Is this still an issue for you? For me it redirects quickly, but upon inspecting in Chrome it looks like it _does_ strip the params for me.

I'm using the 'Block and Re-load' option. What option are you using?

**Comment by cherylfahling** [comment]
It's not still an issue for me.

I'm trying to reduce the number of add-ons I use in Chrome.

I'm using a userscript instead: [UTM param stripper](https://greasyfork.org/en/scripts/4056-utm-param-stripper)

Thank you!

**Comment by newhouse** [comment]
No problem, and thanks for trying out the extension!

**Comment by cherylfahling** [comment]
You're welcome.  It's the best of it's kind!
