### ISSUE TITLE
Handle google search results?

### ISSUE THREAD

**Issue by eddiegalvez** [newhouse/url-tracking-stripper#14]
Could it please handle google search results such as 

https://www.google.com/url?sa=t&rct=j&q=&esrc=s&source=web&cd=12&cad=rja&uact=8&ved=0ahUKEwjO6q-Wqf3WAhXpzFQKHVXIDcgQFghnMAs&url=https%3A%2F%2Fultracart.atlassian.net%2Fwiki%2Fdisplay%2Fucdoc%2FTesting%2BInvisible%2BLink%2BTracking&usg=AOvVaw22Rzv9kLaLCEXOnjXnMnLG

**Comment by newhouse** [comment]
Hi @eddiegalvez and thanks for using my extension! So let me see if I'm understanding this. Embedded in the URL you just provided is the target URL, which is:
"https://ultracart.atlassian.net/wiki/display/ucdoc/Testing+Invisible+Link+Tracking"

I'm trying to figure out if you are asking:
a) Intercept _*clicks*_ to "https://www.google.com/url?blahblah&url=https%3A%2F%2Fultracart.atlassian.net%2Fwiki%2Fdisplay%2Fucdoc%2FTesting%2BInvisible%2BLink%2BTracking" and just reduce them to "https://ultracart.atlassian.net/wiki/display/ucdoc/Testing+Invisible+Link+Tracking"

or

b) Scan a page and look for Google Search results like that and change the link to be the target URL before you even click it?

Which are you referring to? Also, where can I see how that URL was generated? Is that a copy/paste from 1 of the results of a google search results page?

**Comment by eddiegalvez** [comment]
The URL I gave as an example is what you get as links when you do a google search, currently.
I would like not to have to bounce via google tracking; thus, I want the example given to indeed reduce the fact that clicking on the url shown at (a) never hits google.com and goes directly to ultracart(etc)

Of course doing (b) achieves the same effect - go directly to the URL, not bounce via google's sneaky link tracking (they modify the status bar so you don't see that it goes through them, which I very much dislike)

**Comment by newhouse** [comment]
Cool, just making sure. I like the idea of doing `(a)`, but doing `(b)` would be outside the scope of this extension. I'll try to get it done. Stay tuned @eddiegalvez ...

**Comment by newhouse** [comment]
haven't forgotten about this @eddiegalvez ...just a bit busy, but have begun working on it.

**Comment by newhouse** [comment]
Hi @eddiegalvez 

Can you try installing this unpublished version of the extension to see if it works as you'd hoped? You'll want to (probably) choose 'Block and reload' stripping method and (definitely) enable the 'Skip Known Redirects' checkbox.

Should be available in a little bit after it hits google's servers:
https://chrome.google.com/webstore/detail/edmiebadjbeiajmakkdoinnpdmmncapj

**Comment by eddiegalvez** [comment]
Seems to be doing the trick!

**Comment by newhouse** [comment]
ok, great @eddiegalvez . I've just updated the "public" version of this extension to 2.0.0 and it should be available within the half hour.

I'd recommend you uninstall that "test" extension I linked to above, and then be sure to update the public extension to 2.0.0 via chrome://extensions/

Thanks!
