### ISSUE TITLE
Not working on YouTube?

### ISSUE THREAD

**Issue by SM91337** [newhouse/url-tracking-stripper#66]
Not sure if the feature has been added yet, but I can't seem to find an extension which removes the outbound tracking of links on YouTube (IE: https://www.youtube.com/redirect?q=) It would be nice to see such thing added.

Many thanks.

**Comment by SM91337** [comment]
I attempted making some code which "Works" sometimes, and sometimes does not.

`var newurl;

document.addEventListener('DOMNodeInserted', OnElementInserted, false);

function OnElementInserted(event) {
    if (typeof(event.target) === 'undefined' && typeof(event.srcElement) === 'undefined') {
        return;
    }

    var target = null;

    if (typeof(event.target) === 'undefined') {
        target = event.srcElement;
    } else {
        target = event.target;
    }

    if (target === null) {
        return;
    }

    var element = event.target;

    if (element.tagName === "A")
        cleanUrl(element);
}

function cleanUrl(url) {
    var index = url.href.indexOf("&q=");

    if (index !== -1) {
        newurl = decodeURIComponent(url.href.split("&q=")[1].split("&")[0].toString());
    } else {
        index = url.href.indexOf("?q=");

        if (index !== -1) {
            newurl = decodeURIComponent(url.href.split("?q=")[1].split("&")[0]);
        }
    }

    url.href = newurl;
    url.src = newurl;
}`

**Comment by newhouse** [comment]
Added in https://github.com/newhouse/url-tracking-stripper/pull/75 thanks!!!
