### ISSUE TITLE
Request to add new query parameter "fbclid"

### ISSUE THREAD

**Issue by patchcali** [newhouse/url-tracking-stripper#74]
It's Facebook's new tracker, and it breaks website caching:

https://community.cloudflare.com/t/facebook-now-adds-fbclid-query-string-to-urls-busting-cloudflares-cache/40355

https://www.reddit.com/r/analytics/comments/9o52yw/parameter_called_fbclid_appearing_in_referrals/

Thanks for your consideration.

**Comment by newhouse** [comment]
Fixed by https://github.com/newhouse/url-tracking-stripper/pull/73 !!!
