### ISSUE TITLE
iOS Mobile app

### ISSUE THREAD

**Issue by myw** [newhouse/url-tracking-stripper#78]
I know an issue isn’t necessarily the best place to ask this question, but I’m wondering if you’ve seen any apps for iOS that perform this functionality, say, by seeing what’s on the clipboard and, if it’s a url, giving you the chance to copy the tracking-removed url to the clipboard instead.

I find that the majority of times I remove tracking identifiers by hand, it’s when I’m messaging a shared link to a friend, which usually happens on my phone. I am not an app developer, but I have considered learning Swift just to be able to write an app like this. If someone else has already beaten me to the punch, I’d be glad for it.

In your research trying to address the issue, have you seen anything like that?

**Comment by newhouse** [comment]
Hey @myw I can't recall seeing something like that, but I have investigated into such a thing before...can't remember finding anything good back then. Good luck! If you find something, please come back and let me know!
