### ISSUE TITLE
Strip utm_name from URLs

### ISSUE THREAD

**Issue by ZzZombo** [newhouse/url-tracking-stripper#8]
Reddit links still have that after being stripped. Awesome extension otherwise.

**Comment by newhouse** [comment]
OMG, so sorry I didn't see this! Not sure why I wasn't receiving notifications...

@ZzZombo can you provide an example URL for me if you're still interested? I'll try to find one on my own, but would be better if you can just provide a working example. Thanks!

**Comment by newhouse** [comment]
@ZzZombo found one:
https://www.reddit.com/r/YouShouldKnow/?utm_content=trending_sr_4&utm_medium=trending_subreddits_bar&utm_source=reddit&utm_name=frontpage

Looks like `utm_name` was already getting stripped out in my browser, but it was not by my extension! I guess they're self-stripping the `utm_*` stuff from the URLs on their own.

Will add `utm_name` to trackers.

**Comment by newhouse** [comment]
Added in v1.4, which is on its way out to Google now.
