### ISSUE TITLE
Url Tracking Stripper breaks GitLab.com branch switcher

### ISSUE THREAD

**Issue by archon810** [newhouse/url-tracking-stripper#81]
See https://gitlab.com/gitlab-org/gitlab-ce/issues/66621.

**Comment by archon810** [comment]
Is this project pretty much dead?

**Comment by newhouse** [comment]
Sorry for the delay...I'd say it's in a coma. I haven't had time lately to update things. I think it needs a bit of an overhaul to support conditionally applying the stripping based on domain matching as well. Sorry. I will try to get to it sometime, but been really busy.

**Comment by newhouse** [comment]
FYI - started working on this...

**Comment by newhouse** [comment]
This should be fixed now in version 5.0.0. Closing.
