### ISSUE TITLE
Broken as of a couple days ago?

### ISSUE THREAD

**Issue by 1337ingDisorder** [newhouse/url-tracking-stripper#82]
For the past couple days I've noticed some tracking stuff slipping through.

The latest example:

https://www.vice.com/en_us/article/bjwjpd/someone-just-moved-a-billion-dollars-in-bitcoin-and-no-one-knows-why?unfurl%3Futm_source=mbfb

**Comment by newhouse** [comment]
Hmm, that's just some shotty web coding there: they've URL-encoded the `&`, resulting in a `%3F`. As it's not part of a redirect (where it might have eventually been caught and stripped), I'm not sure if I'm going to go the route of stripping URL-encoded params at this time. Will consider it, though, in the future.
