### ISSUE TITLE
Breaks support.steampowered.com Steam Support article links

### ISSUE THREAD

**Issue by AmperAndSand** [newhouse/url-tracking-stripper#85]
With this extension enabled, links to specific `support.steampowered.com` Steam Support articles, e.g. https://support.steampowered.com/kb_article.php?ref=8625-wrah-9030 get redirected to the main Steam Support page at https://help.steampowered.com/en/ instead of to the expected article page.

This will not allow you to view the specific articles, probably because the `?ref=8625-wrah-9030` part gets removed. There should either be an exception for this or a way to allow users to configure exceptions for specific URLs.

**Comment by newhouse** [comment]
This should be fixed now in version 5.0.0. Closing.
