### ISSUE TITLE
Please add Amazon

### ISSUE THREAD

**Issue by cherylfahling** [newhouse/url-tracking-stripper#9]
Can you please remove everything after the question mark (?) from Amazon giveaways?

Poll
https://smile.amazon.com/ga/p/3c5173cbe53cb287?nav=amz&fsrc=glp&ref_=pe_2644850_235117830_gde#ln-pl

Twitter
https://smile.amazon.com/ga/p/59eafb91ec2b41c9?nav=amz&fsrc=glp&ref_=pe_2644850_234975030_gde#ts-tw

YouTube
https://smile.amazon.com/ga/p/fa9f12bafd7e4261?nav=amz&fsrc=glp&ref_=pe_2644850_234975030_gde#ln-yt

Thank you!

**Comment by newhouse** [comment]
OMG, so sorry I didn't see this! Not sure why I wasn't receiving notifications...

Let me have a look and get back to you @cherylfahling and @atavic

**Comment by cherylfahling** [comment]
Don't worry about it.  Amazon/Amazon Smile wasn't working right for me on the giveaways, but for some reason it is now.

Thank you!

**Comment by newhouse** [comment]
OK, cool. That's odd it wasn't and then now is working for you. Either way, I don't think that universally blocking _everything_ after a `?` is a good idea. In many cases it's significant to getting the page to load properly.

I have no clue what the significance of the `nav`, `fscr` and `ref_` params are in this case, so I'd need to be more sure that they're used exclusively for tracking purposes before removing them wherever they're encountered. Perhaps if they're not desirable/required on `smile.amazon.com` specifically, I could add domain-specific tracker support...but, again, would need to be convinced so as not to break lots of sites/experiences for users.

I'm going to close this issue for now, but feel free to re-open if you find some supporting evidence want to pursue this more.

Thanks for using my extension!
